name: build and deploy

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "7.0.X"
  AZURE_WEBAPP_NAME: StockGrader
  AZURE_WEBAPP_PACKAGE_PATH: "."
  PUBLISH_PROJECT_FOLDER: StockGraderRelease

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Create App.config
        run: |
             cat > StockGrader/StockGrader.DiscordBot/App.config << 
             EOT
             <?xml version="1.0" encoding="utf-8" ?>
             <configuration>
                  <appSettings>
                      <add key="EndpointUri" value="https://matejgros.documents.azure.com:443/" />
                      <add key="PrimaryKey" value="${{ secrets.PRIMARYKEY  }}" />
                      <add key="ContainerName" value="ysoft_con"/>
                      <add key="DatabaseName" value="ysoft"/>

                      <add key="StockUrl" value="https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv"/>
                      <add key="FileName" value="ARK_ORIGINAL.csv"/>
                      <add key="UserAgentHeader" value="User-Agent"/>
                      <add key="CommonUserAgent" value="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"/>

                      <add key="Token" value="${{ secrets.DISCORD_TOKEN  }}"/>
                      <add key="CommandPrefix" value="!"/>

                  </appSettings>
              </configuration>
              EOT


      - name: Install dependencies
        run: dotnet restore StockGrader/StockGrader.sln

      - name: Build
        run: dotnet build StockGrader/StockGrader.sln --configuration Release --no-restore

      - name: Prepare app for release
        run: dotnet publish StockGrader/StockGrader.DiscordBot/StockGrader.DiscordBot.csproj --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.PUBLISH_PROJECT_FOLDER }}/App_Data/Jobs/Continuous/StockGrader.DiscordBot'

      - name: Deploy app to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.PUBLISH_PROJECT_FOLDER }}"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
