name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.X' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore StockGrader/StockGrader.sln
      
    - name: Build
      run: dotnet build StockGrader/StockGrader.sln --configuration Release --no-restore
    
    - name: Create App.config
      run: |
        echo '<?xml version="1.0" encoding="utf-8" ?>' > src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '<configuration>' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '  <appSettings>' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '    <add key="EndpointUri" value="https://matejgros.documents.azure.com:443/" />' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '    <add key="DatabaseName" value="ysoft" />' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '    <add key="ContainerName" value="ysoft_con" />' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '    <add key="PrimaryKey" value="Q81VjNyyQVrnLsFQAFdtNIVOKAQNvtWfnZakk2tza63x5Y1ixPDPCT6B1cdUpBvJlp14doz6t52kACDb4P4BvA==" />' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '  </appSettings>' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config
        echo '</configuration>' >> src/StockGrader/StockGrader.ExecutableConsoleApp/App.config

    - name: Test
      run: dotnet test StockGrader/StockGrader.sln --no-restore --verbosity normal